version: '3'
services:
  web:
    build: .
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  db_data:
  node_modules:

